### ISSUE TITLE
MVPs 1 && 2 User auth and hosting on heroku

### ISSUE THREAD

**Issue by JOlivier92** [JOlivier92/Dotify#2]
Hey Liz! Just opening an issue for my first two MVPs, I still need to style my sign up and login page, and need to add a bit of logic to change the forms a bit (confirming email on signup, being able to use a username or email to sign in), but the basic functionality works.

Here is my personal checklist of things I still need to do for my splash / login / signup pages:
* Style login/signup pages
* implement logic to have "sign in as demo user" actually carry out sign in function
* implement logic to allow users to enter either their username or email when signing in
* implement logic to check that users enter the same email twice when signing up
* Finish creating hamburger icon on the splash page (low priority)

Let me know if there is anything else I need to do! Thanks for your feedback / help in advance!

**Comment by eshoule** [comment]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in


## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)

Please address the following issues before I close this. Thanks! Good job.
- [x] There are some console warnings when I go to your site. Please fix them.
- [x] There's also a strange error on your signup page (reCAPTCHA?).
- [x]  The login with guest button on your signup page does not work.
- [x]  Style your errors

**Comment by JOlivier92** [comment]
Just finished up styling the errors!
